"""add note timestamp

Revision ID: 6fa7eff479bb
Revises: 
Create Date: 2020-12-25 21:13:19.600828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa7eff479bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_song_name', table_name='song')
    op.drop_table('song')
    op.drop_table('singer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('singer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('song',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('singer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['singer_id'], ['singer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_song_name', 'song', ['name'], unique=False)
    # ### end Alembic commands ###
